services:
  fem:
    image: alfianhs7/fem-be-api:dev
    # ports:
      # - "8081:8080"
    env_file:
      - /home/emokids/tugas-akhir/fem/.env.dev
    networks:
      - md_mongodb-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8081:8081"
    volumes:
      - /home/emokids/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/emokids/certs:/certs
    networks:
      - md_mongodb-network

networks:
  md_mongodb-network:
    name: md_mongodb-network
    external: true
