services:
  fem:
    image: alfianhs7/fem-be-api:dev
    ports:
      - "8081:8080"
    env_file:
      - /home/emokids/tugas-akhir/fem/.env.dev
    networks:
      - md_mongodb-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

networks:
  md_mongodb-network:
    name: md_mongodb-network
    external: true
